version: "3.9"
services:
  python-service:
    image: tristanberkie/eindopdracht_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: user
      MYSQL_PASSWORD: 4321Secret1234
      MYSQL_ROOT_PASSWORD: 4321Secret1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: